"""
app/models/participation.py
────────────────────────────
ExpertParticipation model — join table recording which experts
participated in which case, and their contribution scores.
This is the foundation for the reputation engine in Phase 3.
"""
import enum

from sqlalchemy import Enum, Float, ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin, UUIDMixin


class ParticipationRole(str, enum.Enum):
    """Role the expert played within this case."""
    COUNCIL_MEMBER = "council_member"
    DOMAIN_SPECIALIST = "domain_specialist"


class ExpertParticipation(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "expert_participations"

    # ── Foreign Keys ──────────────────────────────────────────────────────────
    expert_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("experts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    case_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Participation metadata ────────────────────────────────────────────────
    role: Mapped[ParticipationRole] = mapped_column(
        Enum(ParticipationRole),
        default=ParticipationRole.COUNCIL_MEMBER,
        nullable=False,
    )
    recommendation: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        comment="approve | reject | conditional_approve",
    )
    confidence: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Expert's stated confidence 0–100.",
    )
    reasoning: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Full reasoning text produced by this expert.",
    )

    # ── Contribution Scores (populated by reputation engine, Phase 3) ─────────
    quality_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    impact_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    calibration_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    contribution_score: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
        comment="Final weighted contribution: 0.5*quality + 0.3*impact + 0.2*calibration",
    )
    self_critique: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Self-critique generated by the expert if in Recovery Mode.",
    )


    # ── Relationships ─────────────────────────────────────────────────────────
    expert: Mapped["Expert"] = relationship(  # noqa: F821
        "Expert",
        back_populates="participations",
    )
    case: Mapped["Case"] = relationship(  # noqa: F821
        "Case",
        back_populates="participations",
    )

    def __repr__(self) -> str:
        return (
            f"<ExpertParticipation expert={self.expert_id!r} "
            f"case={self.case_id!r} role={self.role!r}>"
        )
