"""
app/models/reflection.py
─────────────────────────
Reflection model — represents a reflection lesson generated by the Court Stenographer.
"""
from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin, UUIDMixin


class Reflection(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "reflections"

    # ── Foreign Keys ──────────────────────────────────────────────────────────
    expert_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("experts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    case_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Content ───────────────────────────────────────────────────────────────
    failure_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        comment="Type of failure (e.g., weak_evidence, logical_flaw, poor_calibration, etc.)",
    )
    lesson: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Detailed reflection lesson for the expert to improve.",
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    expert: Mapped["Expert"] = relationship(  # noqa: F821
        "Expert",
        back_populates="reflections",
    )
    case: Mapped["Case"] = relationship(  # noqa: F821
        "Case",
    )

    def __repr__(self) -> str:
        return f"<Reflection id={self.id!r} expert_id={self.expert_id!r} failure_type={self.failure_type!r}>"
