"""
app/models/success_pattern.py
──────────────────────────────
SuccessPattern model — represents a success pattern generated by the Court Stenographer.
"""
from sqlalchemy import ForeignKey, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base, TimestampMixin, UUIDMixin


class SuccessPattern(UUIDMixin, TimestampMixin, Base):
    __tablename__ = "success_patterns"

    # ── Foreign Keys ──────────────────────────────────────────────────────────
    expert_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("experts.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    case_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Content ───────────────────────────────────────────────────────────────
    success_pattern: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Detailed description of what made this expert's performance successful.",
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    expert: Mapped["Expert"] = relationship(  # noqa: F821
        "Expert",
        back_populates="success_patterns",
    )
    case: Mapped["Case"] = relationship(  # noqa: F821
        "Case",
    )

    def __repr__(self) -> str:
        return f"<SuccessPattern id={self.id!r} expert_id={self.expert_id!r}>"
